import { BadRequestException, Injectable, Logger } from '@nestjs/common';
import axios from 'axios';
import { PrismaService } from '../prisma/prisma.service';

const STOP_WORDS = new Set([
  'the', 'a', 'an', 'is', 'are', 'do', 'does', 'did', 'how', 'can', 'could', 'should', 'would',
  'i', 'my', 'me', 'we', 'you', 'your', 'to', 'of', 'in', 'for', 'on', 'and', 'or', 'what',
  'when', 'where', 'who', 'with', 'about', 'get', 'it', 'this', 'that', 'be', 'at', 'as', 'if',
  'from', 'please', 'help', 'tell', 'know', 'want', 'need', 'there', 'their', 'have', 'has',
]);

export interface KnowledgeHit {
  id: string;
  title: string;
  content: string;
  score: number;
}

export interface AssistantReply {
  answer: string;
  source: string | null;
  suggestions: string[];
}

@Injectable()
export class AIService {
  private readonly logger = new Logger(AIService.name);

  constructor(private prisma: PrismaService) {}

  /** Keyword-scored search across the foundation knowledge base. */
  async searchKnowledge(question: string): Promise<KnowledgeHit[]> {
    const words = (question || '')
      .toLowerCase()
      .split(/[^a-z0-9]+/)
      .filter((w) => w.length > 2 && !STOP_WORDS.has(w));
    if (words.length === 0) return [];

    const entries = await this.prisma.aIKnowledge.findMany({ where: { language: 'en' } });
    const scored = entries
      .map((entry) => {
        const title = entry.title.toLowerCase();
        const hay = (entry.title + ' ' + entry.content).toLowerCase();
        let score = 0;
        for (const word of words) {
          if (title.includes(word)) score += 3;
          else if (hay.includes(word)) score += 1;
        }
        return { id: entry.id, title: entry.title, content: entry.content, score };
      })
      .filter((hit) => hit.score > 0)
      .sort((a, b) => b.score - a.score);
    return scored;
  }

  /** Legacy keyword search kept for existing clients. */
  async search(query: string, language = 'en') {
    const q = (query || '').trim();
    if (!q) return [];
    return this.prisma.aIKnowledge.findMany({
      where: {
        OR: [
          { title: { contains: q, mode: 'insensitive' } },
          { content: { contains: q, mode: 'insensitive' } }
        ],
        language
      },
      take: 10
    });
  }

  /** Example questions shown in the assistant. */
  async suggestions(): Promise<string[]> {
    const entries = await this.prisma.aIKnowledge.findMany({
      where: { language: 'en' },
      orderBy: { createdAt: 'asc' },
      take: 6
    });
    return entries.map((e) => e.title);
  }

  /**
   * Answers a question from the knowledge base. If an OPENAI_API_KEY is
   * configured, the answer is generated by OpenAI grounded on the matched
   * knowledge; otherwise the curated knowledge text is returned directly.
   */
  async ask(question: string): Promise<AssistantReply> {
    const q = (question || '').trim().slice(0, 500);
    if (!q) {
      throw new BadRequestException('Ask a question about the foundation.');
    }
    const suggestions = await this.suggestions();
    const hits = await this.searchKnowledge(q);
    const top = hits[0];

    if (top && top.score >= 2) {
      const grounded = await this.askOpenAI(q, top);
      if (grounded) {
        return { answer: grounded, source: top.title, suggestions };
      }
      return { answer: top.content, source: top.title, suggestions };
    }

    const general = await this.askOpenAI(q);
    if (general) {
      return { answer: general, source: 'AI assistant', suggestions };
    }
    return {
      answer:
        "I don't have verified information about that yet. The foundation team will be happy to help — you can reach them on WhatsApp from the button below.",
      source: null,
      suggestions
    };
  }

  /** Legacy single-answer lookup kept for existing clients. */
  async answer(query: string, language = 'en') {
    const results = await this.search(query, language);
    if (!results || results.length === 0) {
      return null;
    }
    return results[0];
  }

  /**
   * Uses OpenAI when OPENAI_API_KEY is configured. Grounds every answer on
   * the foundation knowledge base so the assistant never invents facts.
   * Returns null (caller falls back) when unconfigured or on any error.
   */
  private async askOpenAI(question: string, context?: KnowledgeHit): Promise<string | null> {
    const apiKey = process.env.OPENAI_API_KEY;
    if (!apiKey) return null;
    try {
      const system =
        'You are the friendly virtual assistant of the Lordina Foundation, a Ghanaian nonprofit. ' +
        'Answer in clear, warm English in at most 120 words. Use ONLY the provided foundation knowledge; ' +
        'if the answer is not in it, say you will connect the person with the team and suggest the WhatsApp chat.';
      const knowledge = context
        ? `Foundation knowledge ("${context.title}"): ${context.content}\n\nQuestion: ${question}`
        : `Question: ${question}\n\n(No matching knowledge entry was found.)`;
      const response = await axios.post(
        'https://api.openai.com/v1/chat/completions',
        {
          model: process.env.OPENAI_MODEL || 'gpt-4o-mini',
          messages: [
            { role: 'system', content: system },
            { role: 'user', content: knowledge }
          ],
          max_tokens: 250,
          temperature: 0.4
        },
        { headers: { Authorization: `Bearer ${apiKey}` }, timeout: 20000 }
      );
      const text: string | undefined = response.data?.choices?.[0]?.message?.content?.trim();
      return text || null;
    } catch (error) {
      this.logger.warn('OpenAI request failed; falling back to the knowledge base.');
      return null;
    }
  }
}
